version: '3.1'

services:

  postgresqldb:
    container_name: postgreSQL
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_rental
    volumes:
      - postgres_database:/var/lib/postgresql/data

volumes:
  postgres_database: